// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4CYgxswwQUaR42YaKisgYfmNoPh5Rzhg',
    appId: '1:596421310346:web:11706418091f4616ae7a73',
    messagingSenderId: '596421310346',
    projectId: 'audio-f6dc0',
    authDomain: 'audio-f6dc0.firebaseapp.com',
    storageBucket: 'audio-f6dc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvFAuOI1YeTXRlJ0rECthwwuHkkaLoss',
    appId: '1:596421310346:android:b950a34d05887aa9ae7a73',
    messagingSenderId: '596421310346',
    projectId: 'audio-f6dc0',
    storageBucket: 'audio-f6dc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFU9b0u4y2wEmx4bcg3dqRTXTQCyrH_U',
    appId: '1:596421310346:ios:856ec85266251e46ae7a73',
    messagingSenderId: '596421310346',
    projectId: 'audio-f6dc0',
    storageBucket: 'audio-f6dc0.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUFU9b0u4y2wEmx4bcg3dqRTXTQCyrH_U',
    appId: '1:596421310346:ios:856ec85266251e46ae7a73',
    messagingSenderId: '596421310346',
    projectId: 'audio-f6dc0',
    storageBucket: 'audio-f6dc0.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4CYgxswwQUaR42YaKisgYfmNoPh5Rzhg',
    appId: '1:596421310346:web:03ad06e86df7d1c4ae7a73',
    messagingSenderId: '596421310346',
    projectId: 'audio-f6dc0',
    authDomain: 'audio-f6dc0.firebaseapp.com',
    storageBucket: 'audio-f6dc0.appspot.com',
  );
}
